apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
spec:
  selector:
    app: todo-backend  # Must match the label in Deployment
  ports:
    - protocol: TCP
      port: 5001        # Cluster-internal port
      targetPort: 5001  # Port where your app is listening
  type: LoadBalancer
